title: Bilingual Insights into the Initial Lexicon
subtitle: The Role of Cognates in Word Acquisition
format:
  prezconf-revealjs:
    include-in-header:
    - file: mathjax-colors.html
    self-contained: true
    from: markdown+emoji
    transition: fade
    progress: true
    preload-iframes: true
    link-external-newwindow: true
author:
  - name: "Gonzalo Garcia-Castro"
    orcid: 0000-0002-8553-4209
echo: false
warning: false
fig-dpi: 800
  
bibliography: assets/references.bib
cls: assets/apa7.csl
scrollable: true
show-slide-number: all
slide-number: c
date: "11/03/2024"
conference: PhD Defence / Departament de Medicina i Ciències de la Vida
location: Barcelona (Spain)